<?xml version="1.0"?>
<package format="3">
  <name>ur_conveyor</name>
  <version>0.0.0</version>
  <description>Conveyor belt simulation: object spawner and belt driver for UR3</description>
  <maintainer email="darshmenon02@gmail.com">darsh</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>ros_gz_sim</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
